version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: triv-webserver
    working_dir: /application
    volumes:
      - ../project/isabels-turnover:/application/project/isabels-turnover
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/:/var/log/nginx
    ports:
      - "83:80"
    depends_on:
      - mysql

  php-fpm:
    build: php-fpm
    container_name: triv-php-fpm
    working_dir: /application
    volumes:
      - ../project/isabels-turnover:/application/project/isabels-turnover
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    ports:
      - "82:3030"

  mysql:
    image: mysql:5.7
    container_name: triv-mysql
    working_dir: /application
    volumes:
      - .:/application
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3416:3306"
